# Generated by Django 3.2.5 on 2021-08-01 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_value', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('purchase_confirmation_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(max_length=50)),
                ('costumer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='products.PurchaseProduct')),
            ],
        ),
    ]
