# Generated by Django 3.2.5 on 2021-08-01 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_value', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('purchase_confirmation_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
