# Generated by Django 3.2.5 on 2021-07-31 01:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('token', models.CharField(blank=True, max_length=250)),
                ('creation_date', models.DateField()),
                ('close_date', models.DateField(blank=True)),
                ('expiration_date', models.DateField(blank=True)),
                ('client_ip', models.CharField(max_length=25)),
            ],
        ),
    ]
