# Generated by Django 3.2.5 on 2021-08-01 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='operator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='purchase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchasemodel', verbose_name='Purchases'),
        ),
    ]
