# Generated by Django 3.2.5 on 2021-07-31 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactionmodel_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Transaction'),
        ),
    ]
